
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-srv #Rama  git
          uri: https://github.com/clementeqp/micro-config-entreno22.git
          search-paths: config-data
  application:
    name: config-srv

