
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka-multi-instances
          uri: https://github.com/clementeqp/microservicios-SpringBoot-2022.git
          search-paths: config-data
  application:
    name: config-srv

